title: Helping Ukraine
paginate: 5
theme: PaperMod
baseURL: https://helpingua.es/

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true


languages:
    en:
        LanguageName: ":gb: English"
        weight: 1
    es:
        LanguageName: ":es: Spanish"
        languageAltTitle: Spanish
        weight: 2

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Helping Ukraine
  description: "Helping Ukraine"
  keywords: []
  author:
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: false
  displayFullLangName: true

  # Goal params
  goalTotal: 1950
  goalCurrent: 785
  goalDonators: 12

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"



  # home-info mode
  homeInfoParams:
    Title: "Helping Ukraine"
    Content:

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

# menu:
#   main:
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai